services:
  - type: web
    name: metreyar-api
    env: python
    plan: free
    rootDir: .  # تغییر از 'backend' به '.' (ریشه)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        value: sqlite:///./metreyar.db
      - key: SECRET_KEY
        generateValue: true
