services:
  - type: web
    name: metreyar-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    env: python
    autoDeploy: true
    plan: free
    build:
      context: .
